class Player {
  // I should probably make a generic 'game' prop, and then attach some game instance to that.
  //   game: CardGame;
  /**
   *
   * @param {String} socketId - socket id generated by socket.io
   * @param {String} roomName - name of room player is in
   */
  constructor(socketId, roomName) {
    this.gamename = "";
    this.socketId = socketId;
    this.room = roomName;
    this.hand = [];
    this.points = 0;
    this.phase = 1;
  }
}

class GameRoom {
  roomName;
  users = [];
  skipped = [];
  playerUp;
  drawPile = [];
  discardPile = [];

  constructor(roomName) {
    this.roomName = roomName;
    this.generateDeck();
    this.shuffle(this.drawPile);
  }

  generateDeck() {
    for (let color = 1; color < 5; color++) {
      for (let value = 0; value < 12; value++) {
        const card = {
          value,
          text: value.toFixed(0),
          color,
        };
        this.drawPile.push(card);
      }
    }
  }

  shuffle(cards) {
    // for twice the length of the card set
    for (let i = 0; i < cards.length * 2; i++) {
      // get random card index
      const randIdx = Math.floor(Math.random() * cards.length);

      // swap with first index
      const temp = cards[randIdx];
      cards[randIdx] = cards[0];
      cards[0] = temp;
    }
  }
}

module.exports = { Player, GameRoom };
